"""
パラメータ定義とカテゴリ分類
"""

from typing import Dict, List, Any, Optional
from dataclasses import dataclass
from .optimizer_templates import get_optimizer_template_loader


@dataclass
class ParameterConfig:
    """パラメータ設定クラス"""

    name: str
    display_name: str
    param_type: str  # "str", "int", "float", "bool", "list"
    default_value: Any
    required: bool = False
    help_text: str = ""
    choices: Optional[List[Any]] = None
    placeholder_text: str = ""


# 新しいタブ構成のパラメータ定義(サブカテゴリ別)
PARAMETER_CATEGORIES = {
    "モデル・出力": [
        # 1.1 モデルパス設定
        ParameterConfig(
            "dit",
            "--dit",
            "str",
            "D:/model/diffusers/Qwen-Image/transformer/diffusion_pytorch_model-00001-of-00009.safetensors",
            True,
            "DiTチェックポイントパス",
            None,
            "例: D:/model/qwen/transformer/model.safetensors",
        ),
        ParameterConfig(
            "vae",
            "--vae",
            "str",
            "D:/model/diffusers/Qwen-Image/vae/diffusion_pytorch_model.safetensors",
            True,
            "VAEチェックポイントパス",
            None,
            "例: D:/model/qwen/vae/model.safetensors",
        ),
        ParameterConfig(
            "vae_dtype",
            "--vae_dtype",
            "str",
            "fp16",
            False,
            "VAEデータ型",
            ["fp16", "fp32", "bf16"],
        ),
        ParameterConfig(
            "text_encoder",
            "--text_encoder",
            "str",
            "D:/model/diffusers/Qwen-Image/text_encoder/model-00001-of-00004.safetensors",
            True,
            "テキストエンコーダーパス",
            None,
            "例: D:/model/qwen/text_encoder/model.safetensors",
        ),
        # 2.1 基本出力設定
        ParameterConfig(
            "output_dir",
            "--output_dir",
            "str",
            "D:/dataset/qwen/chara_dataset/output",
            True,
            "学習後モデル出力先",
            None,
            "例: D:/output/my_model",
        ),
        ParameterConfig(
            "output_name",
            "--output_name",
            "str",
            "chara_qwen-lora",
            True,
            "出力ファイル名",
            None,
            "例: my_character_lora",
        ),
        ParameterConfig(
            "resume",
            "--resume",
            "str",
            "",
            False,
            "学習再開用state",
            None,
            "例: D:/checkpoints/last_state.safetensors",
        ),
        # 2.2 保存スケジュール設定
        ParameterConfig(
            "save_every_n_epochs",
            "--save_every_n_epochs",
            "int",
            1,
            True,
            "Nエポックごとに保存",
        ),
        ParameterConfig(
            "save_every_n_steps",
            "--save_every_n_steps",
            "int",
            0,
            False,
            "Nステップごとに保存",
            None,
            "例: 100, 500, 1000",
        ),
        ParameterConfig(
            "save_last_n_epochs",
            "--save_last_n_epochs",
            "int",
            0,
            False,
            "最後のNエポックを保存",
            None,
            "例: 2, 5, 10",
        ),
        ParameterConfig(
            "save_last_n_epochs_state",
            "--save_last_n_epochs_state",
            "int",
            0,
            False,
            "最後のNエポックstateを保存",
            None,
            "例: 2, 5, 10",
        ),
        ParameterConfig(
            "save_last_n_steps",
            "--save_last_n_steps",
            "int",
            0,
            False,
            "最後のNステップを保存",
            None,
            "例: 100, 500, 1000",
        ),
        ParameterConfig(
            "save_last_n_steps_state",
            "--save_last_n_steps_state",
            "int",
            0,
            False,
            "最後のNステップstateを保存",
            None,
            "例: 100, 500, 1000",
        ),
        ParameterConfig(
            "save_state",
            "--save_state",
            "str",
            "",
            False,
            "学習状態も保存",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "save_state_on_train_end",
            "--save_state_on_train_end",
            "str",
            "",
            False,
            "学習終了時にstateを保存",
            None,
            "オプション: 必要に応じて入力",
        ),
        # 2.3 メタデータ設定
        ParameterConfig(
            "metadata_title",
            "--metadata_title",
            "str",
            "",
            False,
            "モデルタイトル",
            None,
            "例: My Character LoRA v1.0",
        ),
        ParameterConfig(
            "metadata_author",
            "--metadata_author",
            "str",
            "",
            False,
            "モデル作者名",
            None,
            "例: YourName",
        ),
        ParameterConfig(
            "metadata_description",
            "--metadata_description",
            "str",
            "",
            False,
            "モデル説明",
            None,
            "例: アニメキャラクター用LoRAモデル",
        ),
        ParameterConfig(
            "metadata_license",
            "--metadata_license",
            "str",
            "",
            False,
            "モデルライセンス",
            None,
            "例: MIT, CC BY-SA 4.0",
        ),
        ParameterConfig(
            "metadata_tags",
            "--metadata_tags",
            "str",
            "",
            False,
            "モデルタグ",
            None,
            "例: character, anime, lora",
        ),
        ParameterConfig(
            "no_metadata",
            "--no_metadata",
            "str",
            "",
            False,
            "メタデータを出力先モデルに保存しない",
            None,
            "オプション: 必要に応じて入力",
        ),
    ],
    "基本学習": [
        # 3.3.1 基本パラメータ
        ParameterConfig(
            "config_file",
            "--config_file",
            "str",
            "",
            False,
            "設定ファイル(.toml)のパス",
            None,
            "例: D:/configs/training_config.toml",
        ),
        ParameterConfig(
            "dataset_config",
            "--dataset_config",
            "str",
            "D:/dataset/qwen/chara_dataset/chara_dataset.toml",
            True,
            "データセット設定ファイル",
            None,
            "例: D:/dataset/config/dataset.toml",
        ),
        ParameterConfig(
            "max_train_steps",
            "--max_train_steps",
            "int",
            0,
            False,
            "学習ステップ数",
            None,
            "例: 1000, 5000, 10000",
        ),
        ParameterConfig(
            "max_train_epochs",
            "--max_train_epochs",
            "int",
            5,
            True,
            "学習エポック数",
        ),
        ParameterConfig(
            "seed",
            "--seed",
            "int",
            42,
            True,
            "学習時の乱数seed",
        ),
        ParameterConfig(
            "training_comment",
            "--training_comment",
            "str",
            "",
            False,
            "メタデータに記録する任意のコメント文字列",
            None,
            "例: 学習バッチ1回目",
        ),
        # 3.3.2 データローダー設定
        ParameterConfig(
            "max_data_loader_n_workers",
            "--max_data_loader_n_workers",
            "int",
            0,
            False,
            "DataLoaderの最大プロセス数",
            None,
            "例: 2, 4, 8",
        ),
        ParameterConfig(
            "persistent_data_loader_workers",
            "--persistent_data_loader_workers",
            "str",
            "",
            True,
            "DataLoaderワーカーを持続",
            None,
            "オプション: 必要に応じて入力",
        ),
        # 3.3.3 最適化設定
        ParameterConfig(
            "gradient_checkpointing",
            "--gradient_checkpointing",
            "str",
            "",
            True,
            "勾配チェックポイント:有効にするとVRAM使用量削減に効果あり",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "gradient_accumulation_steps",
            "--gradient_accumulation_steps",
            "int",
            1,
            False,
            "勾配蓄積ステップ数",
            None,
            "例: 1, 2, 4, 8",
        ),
        ParameterConfig(
            "mixed_precision",
            "--mixed_precision",
            "str",
            "bf16",
            True,
            "混合精度:accelerateと同じbf16推奨",
            ["no", "fp16", "bf16"],
        ),
        ParameterConfig(
            "blocks_to_swap",
            "--blocks_to_swap",
            "int",
            40,
            True,
            "VRAMからデータの一部をメインメモリに退避:推奨範囲0~45",
        ),
        ParameterConfig(
            "max_grad_norm",
            "--max_grad_norm",
            "float",
            0.0,
            False,
            "勾配正規化の最大norm",
            None,
            "例: 0.5, 1.0, 2.0",
        ),
    ],
    "オプティマイザー・学習率": [
        # 3.4 オプティマイザー設定
        ParameterConfig(
            "optimizer_type",
            "--optimizer_type",
            "str",
            "AdamW8bit",
            True,
            "オプティマイザの種類",
            get_optimizer_template_loader().get_optimizer_choices(),
        ),
        # 3.5 学習率設定
        ParameterConfig(
            "learning_rate",
            "--learning_rate",
            "str",
            "1e-4",
            True,
            "学習率（例: 1e-4, 5e-5）",
            None,
            "例: 1e-4, 5e-5, 2e-6",
        ),
        ParameterConfig(
            "lr_scheduler",
            "--lr_scheduler",
            "str",
            "cosine_with_restarts",
            True,
            "学習率スケジューラ",
            [
                "constant",
                "linear",
                "cosine",
                "cosine_with_restarts",
                "polynomial",
                "constant_with_warmup",
            ],
        ),
        ParameterConfig(
            "lr_warmup_steps",
            "--lr_warmup_steps",
            "int",
            200,
            True,
            "ウォームアップステップ数:Prodigyは0推奨",
        ),
        ParameterConfig(
            "lr_decay_steps",
            "--lr_decay_steps",
            "int",
            0,
            False,
            "減衰ステップ数",
            None,
            "例: 500, 1000, 2000",
        ),
        ParameterConfig(
            "lr_scheduler_num_cycles",
            "--lr_scheduler_num_cycles",
            "int",
            3,
            True,
            "リスタート回数",
        ),
        ParameterConfig(
            "lr_scheduler_power",
            "--lr_scheduler_power",
            "float",
            1.0,
            False,
            "polynomial power",
            None,
            "例: 0.5, 1.0, 2.0",
        ),
        ParameterConfig(
            "lr_scheduler_min_lr_ratio",
            "--lr_scheduler_min_lr_ratio",
            "float",
            0.0,
            False,
            "最小学習率比率",
            None,
            "例: 0.0, 0.1, 0.2",
        ),
        ParameterConfig(
            "lr_scheduler_timescale",
            "--lr_scheduler_timescale",
            "int",
            0,
            False,
            "逆平方根タイムスケール",
            None,
            "例: 100, 500, 1000",
        ),
        ParameterConfig(
            "lr_scheduler_type",
            "--lr_scheduler_type",
            "str",
            "",
            False,
            "カスタムスケジューラモジュール",
            None,
            "例: my_custom_scheduler",
        ),
    ],
    "ネットワーク": [
        # 4.1 ネットワーク設定
        ParameterConfig(
            "network_dim",
            "--network_dim",
            "int",
            8,
            True,
            "ネットワーク次元数",
            None,
            "例: 8, 16, 32, 64",
        ),
        ParameterConfig(
            "network_alpha",
            "--network_alpha",
            "float",
            4,
            True,
            "LoRA重み調整alpha値",
            None,
            "例: 1, 4, 8, 16",
        ),
        ParameterConfig(
            "network_module",
            "--network_module",
            "str",
            "networks.lora_qwen_image",
            True,
            "学習対象ネットワークモジュール",
            None,
            "例: networks.lora_qwen_image",
        ),
        ParameterConfig(
            "network_weights",
            "--network_weights",
            "str",
            "",
            False,
            "ネットワークの初期重み",
            None,
            "例: D:/weights/previous_lora.safetensors",
        ),
        ParameterConfig(
            "network_dropout",
            "--network_dropout",
            "float",
            None,
            False,
            "ネットワークdropout率",
            None,
            "例: 0.1, 0.2, 0.3",
        ),
        ParameterConfig(
            "dim_from_weights",
            "--dim_from_weights",
            "str",
            "",
            False,
            "重みから次元を自動決定",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "scale_weight_norms",
            "--scale_weight_norms",
            "float",
            None,
            False,
            "重みの値をスケーリング",
            None,
            "例: 0.5, 1.0, 2.0",
        ),
        ParameterConfig(
            "network_args",
            "--network_args",
            "str",
            "",
            False,
            "ネットワーク追加引数",
            None,
            "例: rank_dropout=0.1",
        ),
        ParameterConfig(
            "base_weights",
            "--base_weights",
            "str",
            "",
            False,
            "学習前にマージするネットワーク重み",
            None,
            "例: D:/weights/base_lora.safetensors",
        ),
        ParameterConfig(
            "base_weights_multiplier",
            "--base_weights_multiplier",
            "str",
            "",
            False,
            "ベース重みの倍率",
            None,
            "例: 0.5, 1.0, 1.5",
        ),
        # 4.2 タイムステップ設定
        ParameterConfig(
            "timestep_sampling",
            "--timestep_sampling",
            "str",
            "qwen_shift",
            True,
            "タイムステップサンプリング手法",
            None,
            "例: qwen_shift, uniform",
        ),
        ParameterConfig(
            "weighting_scheme",
            "--weighting_scheme",
            "str",
            "logit_normal",
            True,
            "重み付けスキーム",
            choices=["none", "sigma_sqrt", "logit_normal", "mode", "cosine"],
        ),
        ParameterConfig(
            "guidance_scale",
            "--guidance_scale",
            "float",
            3.5,
            True,
            "埋め込みクラシファイアフリーガイダンススケール",
        ),
        ParameterConfig(
            "discrete_flow_shift",
            "--discrete_flow_shift",
            "float",
            1.0,
            False,
            "離散フローシフト",
            None,
            "例: 0.5, 1.0, 2.0",
        ),
        ParameterConfig(
            "sigmoid_scale",
            "--sigmoid_scale",
            "float",
            None,
            False,
            "sigmoidスケール",
            None,
            "例: 0.5, 1.0, 2.0",
        ),
        ParameterConfig(
            "logit_mean",
            "--logit_mean",
            "float",
            None,
            False,
            "logit_normal重み付けの平均",
            None,
            "例: 0.0, 0.5, 1.0",
        ),
        ParameterConfig(
            "logit_std",
            "--logit_std",
            "float",
            None,
            False,
            "logit_normal重み付けのstd",
            None,
            "例: 0.1, 0.5, 1.0",
        ),
        ParameterConfig(
            "mode_scale",
            "--mode_scale",
            "float",
            None,
            False,
            "モード重み付けスキームのスケール",
            None,
            "例: 0.5, 1.0, 2.0",
        ),
        ParameterConfig(
            "min_timestep",
            "--min_timestep",
            "int",
            0,
            False,
            "最小タイムステップ",
            None,
            "例: 0, 50, 100",
        ),
        ParameterConfig(
            "max_timestep",
            "--max_timestep",
            "int",
            1000,
            False,
            "最大タイムステップ",
            None,
            "例: 800, 1000, 1200",
        ),
        ParameterConfig(
            "preserve_distribution_shape",
            "--preserve_distribution_shape",
            "str",
            "",
            False,
            "元の分布形状を保持",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "show_timesteps",
            "--show_timesteps",
            "str",
            None,
            False,
            "タイムステップを画像またはコンソールに表示",
            None,
            "例: image, console",
        ),
    ],
    "パフォーマンス": [
        # 5.1 アテンション最適化（6項目）
        ParameterConfig(
            "sdpa",
            "--sdpa",
            "str",
            "",
            True,
            "SDPA使用",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "flash_attn",
            "--flash_attn",
            "str",
            "",
            False,
            "FlashAttention使用",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "sage_attn",
            "--sage_attn",
            "str",
            "",
            False,
            "SageAttention使用(推論専用)",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "xformers",
            "--xformers",
            "str",
            "",
            False,
            "xformers使用",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "flash3",
            "--flash3",
            "str",
            "",
            False,
            "FlashAttention 3使用",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "split_attn",
            "--split_attn",
            "str",
            "",
            False,
            "分割attention",
            None,
            "オプション: 必要に応じて入力",
        ),
        # 5.2 精度・メモリ最適化（5項目）
        ParameterConfig(
            "fp8_base",
            "--fp8_base",
            "str",
            "",
            True,
            "base modelにfp8使用",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "fp8_scaled",
            "--fp8_scaled",
            "str",
            "",
            False,
            "DiTにスケーリングfp8使用",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "fp8_vl",
            "--fp8_vl",
            "str",
            "",
            False,
            "Text Encoderにfp8使用",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "img_in_txt_in_offloading",
            "--img_in_txt_in_offloading",
            "str",
            "",
            False,
            "img_inとtxt_inをCPUにオフロード",
            None,
            "オプション: 必要に応じて入力",
        ),
        # 5.3 コンパイル最適化（4項目）
        ParameterConfig(
            "dynamo_backend",
            "--dynamo_backend",
            "str",
            None,
            False,
            "dynamoバックエンド",
            None,
            "例: inductor, aot_eager",
        ),
        ParameterConfig(
            "dynamo_mode",
            "--dynamo_mode",
            "str",
            "default",
            False,
            "dynamoモード",
            None,
            "例: default, reduce-overhead",
        ),
        ParameterConfig(
            "dynamo_fullgraph",
            "--dynamo_fullgraph",
            "str",
            "",
            False,
            "dynamoのfullgraphモード",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "dynamo_dynamic",
            "--dynamo_dynamic",
            "str",
            "",
            False,
            "dynamoのdynamicモード",
            None,
            "オプション: 必要に応じて入力",
        ),
        # 5.4 分散処理設定（3項目）
        ParameterConfig(
            "ddp_timeout",
            "--ddp_timeout",
            "int",
            None,
            False,
            "DDPタイムアウト（分）",
            None,
            "例: 30, 60, 120",
        ),
        ParameterConfig(
            "ddp_gradient_as_bucket_view",
            "--ddp_gradient_as_bucket_view",
            "str",
            "",
            False,
            "DDPでgradient_as_bucket_view有効",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "ddp_static_graph",
            "--ddp_static_graph",
            "str",
            "",
            False,
            "DDPでstatic_graph有効",
            None,
            "オプション: 必要に応じて入力",
        ),
    ],
    "ログ・監視": [
        # 6.1 ログ出力設定（8項目）
        ParameterConfig(
            "logging_dir",
            "--logging_dir",
            "str",
            "./logs",
            False,
            "ログ出力ディレクトリ",
            None,
            "例: D:/logs, ./training_logs",
        ),
        ParameterConfig(
            "log_with",
            "--log_with",
            "str",
            "tensorboard",
            False,
            "ログツール",
            ["tensorboard", "wandb", "all"],
        ),
        ParameterConfig(
            "log_prefix",
            "--log_prefix",
            "str",
            None,
            False,
            "ログディレクトリ名のプレフィックス",
            None,
            "例: exp1, character_training",
        ),
        ParameterConfig(
            "log_tracker_name",
            "--log_tracker_name",
            "str",
            None,
            False,
            "tracker名",
            None,
            "例: qwen_training",
        ),
        ParameterConfig(
            "wandb_run_name",
            "--wandb_run_name",
            "str",
            None,
            False,
            "wandb実行名",
            None,
            "例: character_lora_v1",
        ),
        ParameterConfig(
            "wandb_api_key",
            "--wandb_api_key",
            "str",
            None,
            False,
            "WandB APIキー",
            None,
            "例: abcd1234567890efgh",
        ),
        ParameterConfig(
            "log_tracker_config",
            "--log_tracker_config",
            "str",
            None,
            False,
            "trackerの設定ファイルパス",
            None,
            "例: D:/configs/tracker.json",
        ),
        ParameterConfig(
            "log_config",
            "--log_config",
            "str",
            "",
            False,
            "学習設定をログに出力",
            None,
            "オプション: 必要に応じて入力",
        ),
        # 6.2 サンプリング設定（4項目）
        ParameterConfig(
            "sample_every_n_steps",
            "--sample_every_n_steps",
            "int",
            None,
            False,
            "Nステップごとにサンプル出力",
            None,
            "例: 100, 500, 1000",
        ),
        ParameterConfig(
            "sample_at_first",
            "--sample_at_first",
            "str",
            "",
            False,
            "学習前にサンプル出力",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "sample_every_n_epochs",
            "--sample_every_n_epochs",
            "int",
            None,
            False,
            "Nエポックごとにサンプル出力",
            None,
            "例: 1, 2, 5",
        ),
        ParameterConfig(
            "sample_prompts",
            "--sample_prompts",
            "str",
            None,
            False,
            "サンプル出力用プロンプトファイル",
            None,
            "例: D:/prompts/sample_prompts.txt",
        ),
        # 6.3 外部連携設定（HuggingFace等）（8項目）
        ParameterConfig(
            "huggingface_repo_id",
            "--huggingface_repo_id",
            "str",
            None,
            False,
            "HuggingFaceリポジトリ名",
            None,
            "例: username/my-lora-model",
        ),
        ParameterConfig(
            "huggingface_repo_type",
            "--huggingface_repo_type",
            "str",
            None,
            False,
            "HuggingFaceリポジトリタイプ",
            None,
            "例: model, dataset",
        ),
        ParameterConfig(
            "huggingface_path_in_repo",
            "--huggingface_path_in_repo",
            "str",
            None,
            False,
            "リポジトリ内ファイルパス",
            None,
            "例: models/lora.safetensors",
        ),
        ParameterConfig(
            "huggingface_token",
            "--huggingface_token",
            "str",
            None,
            False,
            "HuggingFaceトークン",
            None,
            "例: hf_xxxxxxxxxxxxxxxxxxxx",
        ),
        ParameterConfig(
            "huggingface_repo_visibility",
            "--huggingface_repo_visibility",
            "str",
            None,
            False,
            "リポジトリ公開設定",
            None,
            "例: private, public",
        ),
        ParameterConfig(
            "save_state_to_huggingface",
            "--save_state_to_huggingface",
            "str",
            "",
            False,
            "stateをHuggingFaceに保存",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "resume_from_huggingface",
            "--resume_from_huggingface",
            "str",
            "",
            False,
            "HuggingFaceから学習再開",
            None,
            "オプション: 必要に応じて入力",
        ),
        ParameterConfig(
            "async_upload",
            "--async_upload",
            "str",
            "",
            False,
            "非同期でアップロード",
            None,
            "オプション: 必要に応じて入力",
        ),
    ],
}


def get_all_parameters() -> Dict[str, List[ParameterConfig]]:
    """全パラメータ設定を取得"""
    return PARAMETER_CATEGORIES


def get_parameter_by_name(name: str) -> Optional[ParameterConfig]:
    """パラメータ名から設定を取得"""
    for category_params in PARAMETER_CATEGORIES.values():
        for param in category_params:
            if param.name == name:
                return param
    return None
